### PR TITLE
Amazon Linux installation

### PR DESCRIPTION
**Pull request by g4s8**
Added Amazon Linux install section

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#114](https://github.com/yegor256/zold/issues/114) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#114](https://github.com/yegor256/zold/issues/114); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
The job [#114](https://github.com/yegor256/zold/issues/114) is now out of scope

**Pull request merged**
